version: "3.1"
services:
  api:
    #? Interactive shell
    stdin_open: true
    tty: true

    #? Set container name
    container_name: songs_app_service

    #? Build the auth service
    build:
      context: .
      dockerfile: Dockerfile

    #? Environment Variables
    environment:
      EXPRESS_PORT: 8080
      MONGO_CONNECTION_URL: "yourMongoDBUrl"


    #? Restart if down
    restart: always

    #? Ports
    ports:
      - 8080:8080
